# Generated by Django 4.1.7 on 2023-04-25 11:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainAutoTableModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('articles', models.CharField(blank=True, max_length=255, verbose_name='Articles')),
                ('group', models.CharField(blank=True, max_length=255, verbose_name='Group')),
                ('subgroup', models.CharField(blank=True, max_length=255, verbose_name='SubGroup')),
                ('vendor', models.CharField(blank=True, max_length=255, verbose_name='Vendor')),
                ('vendor_code', models.CharField(blank=True, max_length=255, verbose_name='Vendor Code')),
                ('quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantity')),
                ('req_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Required quantity')),
                ('auto_brand', models.CharField(blank=True, max_length=255, verbose_name='Brand')),
                ('auto_model', models.CharField(blank=True, max_length=255, verbose_name='Model')),
                ('purchase_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Purchase price')),
                ('selling_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Selling price')),
                ('recommend_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Recommend price')),
                ('time_create', models.DateTimeField(auto_now_add=True)),
                ('time_update', models.DateTimeField(auto_now=True)),
                ('is_published', models.BooleanField(default=True)),
                ('content', models.TextField(blank=True)),
                ('content_extra1', models.TextField(blank=True)),
                ('content_extra2', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('margin', models.FloatField(default=1.7, validators=[django.core.validators.MinValueValidator(0)])),
                ('provider', models.CharField(blank=True, max_length=255, verbose_name='Provider')),
                ('currency', models.CharField(blank=True, max_length=255, verbose_name='Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
